spring.datasource.url=jdbc:mariadb://localhost:3306/accountdb
spring.datasource.username=accountuser
spring.datasource.password=acc
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
??: https://7942yongdae.tistory.com/128 [??? ??:????]