### use balance1
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId":1,
  "accountNumber":"1000000000",
  "amount":8000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId":1,
  "accountNumber":"1000000000",
  "amount":3000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId":"5bdd81108a6a4a73a04fee45c631b14d",
  "accountNumber":"1000000000",
  "amount":2000
}

### query transaction
GET http://localhost:8080/transaction/ee927bdd56e941f188068e0fe57b7fef