### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId":1,
  "accountNumber":"1000000000",
  "amount":6000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId":"9b8067a0b64f45bea748ec1a38b295ec",
  "accountNumber":"1000000000",
  "amount":6000
}