### use balance1
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId":1,
  "accountNumber":"1000000000",
  "amount":2000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId":1,
  "accountNumber":"1000000000",
  "amount":3000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId":"6b5f990a338f48a198a6f7c640d51eb2",
  "accountNumber":"1000000000",
  "amount":6000
}

### query transaction
GET http://localhost:8080/transaction/1b50ca7caa054103880d91f2a1a983e5